platform :ios, '8.0'
pod 'AFNetworking', '~> 3.0'
pod 'CocoaLumberjack', '~>2.2'
pod 'ReactiveCocoa', '2.5'
pod 'Masonry', '~> 0.6.4'
pod 'SDWebImage', '~> 3.7.3'
pod 'Fabric'
pod 'Crashlytics'
pod 'DTCoreText', '~> 1.6.17'
